import = ["/home/luckierdodge/.config/alacritty/themes/themes/everforest_dark.toml"]

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "SemiBold"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
startup_mode = "Maximized"
